import Lake from 'src/assets/images/bitcoin-lake.png';
import SpaceX from 'src/assets/images/FeatureSection5.png';
import bitcoinIsland from 'src/assets/images/bitcoinIsland.png';
import Temple from 'src/assets/images/Temple.png';
import Hodl from 'src/assets/images/Hodl.png';
import HandDaimond from 'src/assets/images/HandDaimond.png';
import Volcano from 'src/assets/images/Volcano.png';
import Key from 'src/assets/images/Key.png';
import BigSafe from 'src/assets/images/BigSafe.png';

export const cardData = [
  {
    id: 1,
    imageUrl: SpaceX,
    label: `Leading Crypto Casino. Our Charge`,
    text: `binobi`,
    secondLabel: `Как заработать на криптовалютах`,
    postData: `2022-07-07`,
    color: `#992d2d`,
    width: 120,
    height: 120,
  },
  {
    id: 2,
    imageUrl: Lake,
    label: `Mining & Staking up to 100% APY`,
    text: `binobi`,
    secondLabel: `АМА с CZ на Reddit 21 мая 2022 года `,
    postData: `2022-07-07`,
    color: `#18af31`,
    width: 108,
    height: 108,
  },
  {
    id: 3,
    imageUrl: bitcoinIsland,
    label: `Cashback up to`,
    text: `binobi`,
    secondLabel: `Как заработать на криптовалютах `,
    postData: `2022-07-23`,
    color: `#544b1d`,
    percent: `25%`,
    width: 106,
    height: 106,
  },
  {
    id: 4,
    imageUrl: Temple,
    label: `Cashback up to`,
    text: `binobi`,
    secondLabel: `Как заработать на криптовалютах `,
    postData: `2022-07-23`,
    color: `#c2b3e8`,
    percent: `25%`,
    width: 108,
    height: 108,
  },
  {
    id: 5,
    imageUrl: Hodl,
    label: `Leading Crypto Casino. Our Charge`,
    text: `binobi`,
    secondLabel: `Как заработать на криптовалютах `,
    postData: `2022-07-23`,
    color: `#bc5d00`,
    percent: `25%`,
    width: 140,
    height: 140,
  },
  {
    id: 6,
    imageUrl: HandDaimond,
    label: `Mining & Staking up to 100% APY`,
    text: `binobi`,
    secondLabel: `Как заработать на криптовалютах `,
    postData: `2022-07-23`,
    color: `#5fbf01`,
    percent: `25%`,
    width: 121,
    height: 121,
  },
  {
    id: 7,
    imageUrl: Volcano,
    label: `Leading Crypto Casino. Our Charge`,
    text: `binobi`,
    secondLabel: `Как заработать на криптовалютах `,
    postData: `2022-07-23`,
    color: `#992d2d`,
    percent: `25%`,
    width: 141,
    height: 141,
  },
  {
    id: 8,
    imageUrl: Key,
    label: `Mining & Staking up to 100% APY`,
    text: `binobi`,
    secondLabel: `Как заработать на криптовалютах `,
    postData: `2022-07-23`,
    color: `#992d2d`,
    percent: `25%`,
    width: 121,
    height: 121,
  },
  {
    id: 8,
    imageUrl: BigSafe,
    label: `Mining & Staking up to 100% APY`,
    text: `binobi`,
    secondLabel: `Как заработать на криптовалютах `,
    postData: `2022-07-23`,
    color: `#992d2d`,
    percent: `25%`,
    width: 100,
    height: 100,
  },
];
